schooltje/urls.py
from django.conf.urls import url

from . import views

app_name = 'schooltje'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^richtingen$', views.richtingen, name='richtingen'),
    url(r'^wieiswie$', views.wieiswie, name='wieiswie'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^contactpost$', views.contactpost, name='contactpost'),
]

schopr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('schooltje.urls')),
    url(r'^admin/', admin.site.urls),
]

schooltje/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Richting(models.Model):
    naam = models.CharField(max_length=100)
    omschrijving = models.CharField(max_length=500)
    def __str__(self):
        return "%s" % (self.naam)

class Leraar(models.Model):
    voornaam = models.CharField(max_length=100)
    naam = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='images')
    email = models.CharField(max_length=300)
    def __str__(self):
        return "%s %s" % (self.voornaam, self.naam)

class Klas(models.Model):
    naam = models.CharField(max_length=100)
    numerieke_code = models.IntegerField()
    richting = models.ForeignKey(Richting, on_delete=models.CASCADE)
    leraar = models.ForeignKey(Leraar, on_delete=models.CASCADE)


class Contact(models.Model):
    email = models.CharField(max_length=200)
    nummer = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)

schooltje/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from django.shortcuts import render, redirect
from django.http import Http404 #future: 404 this for all urls that don't exist? https://docs.djangoproject.com/en/1.11/intro/tutorial03/#raising-a-404-error

#can be removed once all functions use return render/redirect instead of HttpResponse & loader
from django.http import HttpResponse

from .models import Richting, Leraar, Klas, Contact

import datetime
def index(request):
    lastPageVisited = setLastPage('schooltje:index', request)

    #time of day greet
    currentTime = datetime.datetime.now().hour
    greeting = ""
    if currentTime < 12 :
        greeting = "Goedemorgen"
    elif currentTime > 12 :
        greeting = "Goedemiddag"
    elif currentTime > 18 :
        greeting = "Goedenavond"

    #check for returning user
    if 'returning' in request.COOKIES:
        greeting += ", welkom terug!"

    context = {'greeting': greeting, 'lastPageVisited':lastPageVisited}

    response = render(request, 'schooltje/index.html', context)

    #all visited pages in session
    if 'uniq_sesh_id' in request.COOKIES:
        sessionkey = request.COOKIES['uniq_sesh_id']
    else:
        sessionkey = request.session.session_key #taking session key once at the start of session and using this as a static, unique session id
        response.set_cookie('uniq_sesh_id', sessionkey) #set a session time to 30 minutes, because set_expiry doesn't work with cookies

    pagesInSession(request, sessionkey, 'index')

    #if cookies get blocked or cause an error (eg too large), return response without setting cookies
    try:
        #first time user set returning cookie
        if not 'returning' in request.COOKIES:
            response.set_cookie('returning', 'true', max_age=10 * 365 * 24 * 60 * 60)
        #saving visited pages in cookie
        if 'pages_visited' in request.COOKIES:
            cookie_pagesVisited = request.COOKIES['pages_visited']
            cookie_pagesVisited += " index"
            response.set_cookie('pages_visited', cookie_pagesVisited)
        else:
            response.set_cookie('pages_visited', 'index')
    except:
        return response
    
    return response

def richtingen(request):
    lastPageVisited = setLastPage('schooltje:richtingen', request)

    richtingen_list = Richting.objects.all()
    context = {'richtingen_list': richtingen_list, 'lastPageVisited':lastPageVisited}

    response = render(request, 'schooltje/richtingen.html', context)

    #all visited pages in session
    if 'uniq_sesh_id' in request.COOKIES:
        sessionkey = request.COOKIES['uniq_sesh_id']
    else:
        sessionkey = request.session.session_key #taking session key once at the start of session and using this as a static, unique session id
        response.set_cookie('uniq_sesh_id', sessionkey) #set a session time to 30 minutes, because set_expiry doesn't work with cookies

    pagesInSession(request, sessionkey, 'richtingen')

    #saving visited pages in cookie
    if 'pages_visited' in request.COOKIES:
        cookie_pagesVisited = request.COOKIES['pages_visited']
        cookie_pagesVisited += " richtingen"
        response.set_cookie('pages_visited', cookie_pagesVisited)
    else:
        response.set_cookie('pages_visited', 'richtingen')

    return response

def wieiswie(request):
    lastPageVisited = setLastPage('schooltje:wieiswie', request)

    leraren_list = Leraar.objects.all()
    for leraar in leraren_list:
        klassen_list = Klas.objects.filter(leraar_id=leraar.id)
        leraar.klassen = list(klassen_list)

    context = {'leraren_list': leraren_list, 'lastPageVisited':lastPageVisited,}

    response = render(request, 'schooltje/wieiswie.html', context)

    #all visited pages in session
    if 'uniq_sesh_id' in request.COOKIES:
        sessionkey = request.COOKIES['uniq_sesh_id']
    else:
        sessionkey = request.session.session_key #taking session key once at the start of session and using this as a static, unique session id
        response.set_cookie('uniq_sesh_id', sessionkey) #set a session time to 30 minutes, because set_expiry doesn't work with cookies

    pagesInSession(request, sessionkey, 'wieiswie')

    #saving visited pages in cookie
    if 'pages_visited' in request.COOKIES:
        cookie_pagesVisited = request.COOKIES['pages_visited']
        cookie_pagesVisited += " wieiswie"
        response.set_cookie('pages_visited', cookie_pagesVisited)
    else:
        response.set_cookie('pages_visited', 'wieiswie')

    return response

def contact(request):
    lastPageVisited = setLastPage('schooltje:contact', request)

    context = {'lastPageVisited':lastPageVisited,}
    response = render(request, 'schooltje/contact.html', context)

    #all visited pages in session
    if 'uniq_sesh_id' in request.COOKIES:
        sessionkey = request.COOKIES['uniq_sesh_id']
    else:
        sessionkey = request.session.session_key #taking session key once at the start of session and using this as a static, unique session id
        response.set_cookie('uniq_sesh_id', sessionkey) #set a session time to 30 minutes, because set_expiry doesn't work with cookies

    pagesInSession(request, sessionkey, 'contact')

    #saving visited pages in cookie
    if 'pages_visited' in request.COOKIES:
        cookie_pagesVisited = request.COOKIES['pages_visited']
        cookie_pagesVisited += " contact"
        response.set_cookie('pages_visited', cookie_pagesVisited)
    else:
        response.set_cookie('pages_visited', 'contact')

    return response

    #future: accept url parameter for error message ("bericht verstuurd")? https://stackoverflow.com/questions/17202861/django-no-reverse-match-with-arguments

def contactpost(request):
    new_entry = Contact(email=request.POST['email'], nummer=request.POST['nummer'], content=request.POST['content'])
    new_entry.save()

    return redirect('schooltje:contact')

def setLastPage(page, request):
    #getting last visited page and then setting it to current page (session)
    lastPageVisited = request.session.get('lastPageVisited',page)
    request.session['lastPageVisited'] = page

    return lastPageVisited

#all visited pages in session
def pagesInSession(request, sessionkey, page):
    with open('sessions.json', 'r') as f:
        data = json.load(f)

    with open('sessions.json', 'w') as f:
        if sessionkey in data:
            data[sessionkey] += " " + page 
            json.dump(data, f)
        else:
            data[sessionkey] = page
            json.dump(data, f)

schooltje/templates/schooltje/base.html
<head>
    <!-- meta tags, ... -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- future: move active class to appropriate page -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li {% block nav-index %}{% endblock %}><a href="{% url 'schooltje:index' %}">Home</a></li>
                    <li {% block nav-richtingen %}{% endblock %}><a href="{% url 'schooltje:richtingen' %}">Ons Aanbod</a></li>
                    <li {% block nav-wieiswie %}{% endblock %}><a href="{% url 'schooltje:wieiswie' %}">Wie is wie</a></li>
                    <li {% block nav-contact %}{% endblock %}><a href="{% url 'schooltje:contact' %}">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'admin:index' %}">Intranet</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <a href="{% url lastPageVisited %}">< vorige pagina</a><br><br>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>

schooltje/templates/schooltje/contact.html
{% extends 'schooltje/base.html' %}
{% block nav-contact %}class="active"{% endblock %}

{% block content %}

<h1>Contact</h1>

<form action="{% url 'schooltje:contactpost' %}" method="post">
{% csrf_token %}
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" id="email" required/>
    </div>

    <div class="form-group">    
        <label for="nummer">Telefoonnummer</label>
        <input type="number" class="form-control" name="nummer" id="nummer" required/>
    </div>

    <div class="form-group">
        <label for="content">Bericht</label>
        <textarea class="form-control" cols="50" rows="4" name="content" id="content" required></textarea>
    </div>

    <button type="submit" class="btn btn-default">Versturen</button>
</form>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}

schooltje/templates/schooltje/index.html
{% extends 'schooltje/base.html' %}
{% block nav-index %}class="active"{% endblock %}

{% block content %}
    <div>
        <p>{{ greeting }}</p>
        <p>Kijk rond op onze website of klik door naar het <a href="{% url 'schooltje:contact' %}">contactformulier</a> voor verdere vragen.</p>
    </div>
{% endblock %}

schooltje/templates/schooltje/richtingen.html
{% extends 'schooltje/base.html' %}
{% block nav-richtingen %}class="active"{% endblock %}

{% block content %}

<h1>Ons aanbod</h1>

{% if richtingen_list %}
    {% for richting in richtingen_list %}

        <div>
            <h3>{{ richting.naam }}</h3>
            <p>{{ richting.omschrijving }}</p>
        </div>

    {% endfor %}
{% else %}
    <p>Er zijn geen richtingen beschikbaar.</p>
{% endif %}

{% endblock %}

schooltje/templates/schooltje/wieiswie.html
{% extends 'schooltje/base.html' %}
{% block nav-wieiswie %}class="active"{% endblock %}

{% load staticfiles %}

{% block content %}

<h1>Het personeel</h1>

{% if leraren_list %}
    {% for leraar in leraren_list %}

        <div>
            <h3>{{ leraar.voornaam }} {{ leraar.naam }} </h3>
            <div><p>{{ leraar.email }}</p></div>
            <div><img src="{% static leraar.foto %}" alt="foto leraar" style="max-width: 20%; max-height: 200px"/></div>
            <div>Klassen:
            {% if leraar.klassen %}
                <ul>
                {% for klas in leraar.klassen %}
                    <li>{{ klas.richting }}, {{ klas.naam }}</li>
                {% endfor %}
                </ul>
            {% else %}
                Geen beschikbaar
            {% endif %}
            </div>
        </div>

    {% endfor %}
{% else %}
    <p>Er zijn geen leraren beschikbaar.</p>
{% endif %}

{% endblock %}